# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99ffc03a947b3661b385fa4f3156ea4d0fe358964734420707b4d5cb6df1e49a7b205c84826353cf7cbf9747b4337e5ef48957d6e6b728731c6b8d2288e041d8

test:
  secret_key_base: 4adf2c59db33a50ddfe81a03527f6f1707b6fb53122c75083acc5cd48a646b92d82fa07be3296574edf96ceaf8300798182d53cbbe1c28e188247b4b176afd5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
